devops: ci cd bug fixes

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -14,7 +14,7 @@ on:
 
 jobs:
   prodRelease:
-    if: ${{ inputs.TRIGGER_EVENT == 'push' }}
+    if: ${{ github.event_name == 'push' }}
     name: Continuous Deployment
     runs-on: ubuntu-latest
     steps:
@@ -50,7 +50,7 @@ jobs:
           body: ${{ steps.changelog.outputs.clean_changelog }}
 
   preProdRelease:
-    # if: ${{ inputs.TRIGGER_EVENT == 'workflow_dispatch' }}
+    if: ${{ github.event_name == 'workflow_dispatch' }}
     name: Continuous Deployment
     runs-on: ubuntu-latest
     steps:
@@ -62,17 +62,10 @@ jobs:
           
       - name: Check String
         run: |
-          echo ${{ github.event_name }}
-          # echo "Inputs:"
-          # for input_var in ${{ toJson(github.event_name) }}; do
-          #   input_name=$(echo "$input_var" | cut -d '=' -f1)
-          #   input_value=$(echo "$input_var" | cut -d '=' -f2-)
-          #   echo "$input_name: $input_value"
-          # done
-          # if [[ ${{ github.event.inputs.version }} != *"beta"* ]]; then
-          #   echo "Error: The version does not contain the string beta"
-          #   exit 1
-          # fi
+          if [[ ${{ github.event.inputs.version }} != *"beta"* ]]; then
+            echo "Error: The version does not contain the string beta"
+            exit 1
+          fi
 
       - name: Create Release
         uses: actions/create-release@v1
